apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zp04i27bb-python
  janus-idp.io/tekton: zp04i27bb-python
  backstage.io/kubernetes-id: zp04i27bb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zp04i27bb-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
